// IPC Channel Constants - Shared between main and renderer processes
export const IPC_CHANNEL_HANDLERS = {
  // Login Operations
  LOGIN: 'login',
  REGISTER: 'register',

  // File System Operations
  SELECT_DIRECTORY: 'SELECT_DIRECTORY',
  SELECT_MULTI_DIR: 'SELECT_MULTI_DIR',
  READ_DIRECTORY: 'READ_DIRECTORY',
  READ_MULTI_DIR: 'READ_MULTI_DIR',
  READ_FILE: 'READ_FILE',
  OPEN_FILE: 'OPEN_FILE',
  COPY_FILES: 'COPY_FILES',
  MOVE_FILES: 'MOVE_FILES',
  DELETE_FILE: 'DELETE_FILE',
  IS_EXIST_DIR: 'IS_EXIST_DIR',

  // S3 Operations
  S3_GET_DOWNLOAD_LIST: 'S3_GET_DOWNLOAD_LIST',
  GET_S3_LOCAL_SYNC_WORKDIR: 'GET_S3_LOCAL_SYNC_WORKDIR',
  S3_GET_ALL_STATES: 'S3_GET_ALL_STATES',
  S3_DOWNLOAD_FILES: 'S3_DOWNLOAD_FILES',
  S3_MOVE_OBJECT: 'S3_MOVE_OBJECT',
  S3_UPLOAD_OBJECTS: 'S3_UPLOAD_OBJECTS',
  S3_DELETE_OBJECTS: 'S3_DELETE_OBJECTS',
  S3_DELETE_OBJECTS_DIRECTLY: 'S3_DELETE_OBJECTS_DIRECTLY',
  CHECK_EXIST_TO_DOWNLOAD: 'CHECK_EXIST_TO_DOWNLOAD',

  // FOR BI TOOL
  S3_GET_ALL_BI_STATES: 'S3_GET_ALL_BI_STATES',
  S3_DOWNLOAD_BI_FILES: 'S3_DOWNLOAD_BI_FILES',
  S3_UPLOAD_BI_OBJECTS: 'S3_UPLOAD_BI_OBJECTS',
  S3_DELETE_BI_OBJECTS: 'S3_DELETE_BI_OBJECTS',

  // File Monitoring Operations
  START_FILE_MONITORING: 'start-file-monitoring',
  STOP_FILE_MONITORING: 'stop-file-monitoring',
  STOP_ALL_FILE_MONITORING: 'stop-all-file-monitoring',
  GET_MONITORED_DIRECTORIES: 'get-monitored-directories',
  IS_FILE_MONITORING_ACTIVE: 'is-file-monitoring-active',

  // Legacy Folder Watching (for backward compatibility)
  WATCH_FOLDER: 'WATCH_FOLDER',
  UNWATCH_FOLDER: 'UNWATCH_FOLDER',

  // Events sent from main to renderer
  FOLDER_CHANGED: 'FOLDER_CHANGED',
  FILE_CHANGE_DETECTED: 'FILE_CHANGE_DETECTED',
  FILE_COPIED: 'FILE_COPIED',

  // Download
  GET_DONWLOADS: 'GET_DONWLOADS',
  GET_DOWNLOAD_DLTS: 'GET_DOWNLOAD_DLTS',
  ALLOW_DOWNLOAD_OBJECT_S3: 'ALLOW_DOWNLOAD_OBJECT_S3',
  ALLOW_MOVE_OBJECT_S3: 'ALLOW_MOVE_OBJECT_S3',
  COPY_AND_UPDATE_PATH_DOWNLOAD: 'COPY_AND_UPDATE_PATH_DOWNLOAD',
  SEARCH_DOWNLOAD_HISTORY: 'SEARCH_DOWNLOAD_HISTORY',

  // upload
  ALLOW_UPLOAD_OBJECT_S3: 'ALLOW_UPLOAD_OBJECT_S3',
  SEARCH_UPLOAD_HISTORY: 'SEARCH_UPLOAD_HISTORY',

  APP_VERSION: 'APP_VERSION',
  APP_API_GET_ALL_AWS_STORE: 'APP_API_GET_ALL_AWS_STORE',
  APP_API_GET_DOWNLOAD_ITEMS: 'APP_API_GET_DOWNLOAD_ITEMS',
  APP_API_GET_UPLOAD_ITEMS: 'APP_API_GET_UPLOAD_ITEMS',
  APP_API_GET_DELETE_ITEMS: 'APP_API_GET_DELETE_ITEMS',

  // QA
  QA_API_GETS: 'QA_API_GETS',
  QA_API_INS: 'QA_API_INS',
  QA_API_UPD_BY_ID: 'QA_API_UPD_BY_ID',
  QA_API_UPD_COMPLEX: 'QA_API_UPD_COMPLEX',

} as const; 